blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("search/", views.post_search, name="post_search")
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('summernote/', include('django_summernote.urls')),
    path("api/", include("blog_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/post/includes/comment_form.html
<form action="{% url "blog:post_comment" post.id %}" method="post">
    {% csrf_token %}
    <div class="row">
        <h3>Add a new comment</h3>
        <div class="col mt-2">
            {{ form.name }}
        </div>
        <div class="col mt-2">
            {{ form.email }}
        </div>
        <div class="mt-2">
            {{ form.body }}
            <input type="submit" class="btn btn-primary mb-3" value="Add comment">
        </div>
    </div>
</form>